# Site settings
title: Learning resoruces
description: My learning resources
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://robertncl.github.io/Learning-resource/" # the base hostname & protocol for your site

# Build settings
theme: jekyll-theme-cayman

# ...existing code...
